# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  NodeCount = 1

  (1..NodeCount).each do |i|
    config.vm.define "ug#{i}" do |node|
    
      node.vm.box               = "generic/ubuntu2004"
      # node.vm.box_check_update  = false
      # node.vm.box_version       = "3.3.0"
      node.vm.hostname          = "ug#{i}.example.com"

      node.vm.network "private_network", ip: "172.16.16.1#{i}"
    
      node.vm.provider :libvirt do |v|
        v.memory  = 2048
        v.nested  = true
        v.cpus    = 2
      end
    end
    
  end

end
