# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  NodeCountMaster = 1

  (1..NodeCountMaster).each do |i|
    config.vm.define "kmaster#{i}" do |node|
    
      node.vm.box               = "generic/ubuntu2004"
      # node.vm.box_check_update  = false
      # node.vm.box_version       = "3.3.0"
      node.vm.hostname          = "kmaster#{i}.example.com"

      node.vm.network "private_network", ip: "172.16.16.1#{i}"
    
      node.vm.provider :libvirt do |v|
        v.memory  = 2048
        v.nested  = true
        v.cpus    = 2
      end
    end
    
  end

  # Kubernetes Worker Nodes
  NodeCount = 1

  (1..NodeCount).each do |i|

    config.vm.define "kworker#{i}" do |node|

      node.vm.box               = "generic/ubuntu2004"
      # node.vm.box_check_update  = false
      # node.vm.box_version       = "3.3.0"
      node.vm.hostname          = "kworker#{i}.example.com"

      node.vm.network "private_network", ip: "172.16.16.2#{i}"

      node.vm.provider :libvirt do |v|
        v.memory  = 1024
        v.nested  = true
        v.cpus    = 1
      end

    end

  end

  NodeCountLB = 0

  (1..NodeCountLB).each do |i|

    config.vm.define "lbmaster" do |node|

      node.vm.box               = "generic/ubuntu2004"
      # node.vm.box_check_update  = false
      # node.vm.box_version       = "3.3.0"
      node.vm.hostname          = "lbmaster.example.com"

      node.vm.network "private_network", ip: "172.16.16.31"

      node.vm.provider :libvirt do |v|
        v.memory  = 512
        v.nested  = true
        v.cpus    = 1
      end

    end

  end

end
